# Generated by Django 6.0.6 on 2026-08-04 15:35

import django.db.models.deletion
import pyotp
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge_auth', '0003_otptoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Échecs de connexion consécutifs'),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name="Verrouillé jusqu'à"),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='forge_auth/profile_photos/', verbose_name='Photo de profil'),
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('prefix', models.CharField(db_index=True, editable=False, max_length=12, verbose_name='Préfixe')),
                ('hashed_key', models.CharField(editable=False, max_length=128, verbose_name='Clé (hachée)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernière utilisation')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Révoquée le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'clé API',
                'verbose_name_plural': 'clés API',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LoginAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_attempted', models.CharField(blank=True, default='', max_length=255, verbose_name='Identifiant saisi')),
                ('result', models.CharField(choices=[('success', 'Succès'), ('failure', 'Échec')], max_length=10, verbose_name='Résultat')),
                ('reason', models.CharField(blank=True, default='', max_length=255, verbose_name='Motif')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.CharField(blank=True, default='', max_length=255, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'historique de connexion',
                'verbose_name_plural': 'historiques de connexion',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SessionMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(max_length=255, unique=True, verbose_name='JTI du refresh token')),
                ('user_agent', models.CharField(blank=True, default='', max_length=255, verbose_name='User-Agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='Dernière activité')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Révoquée le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'session',
                'verbose_name_plural': 'sessions',
                'ordering': ('-last_seen_at',),
            },
        ),
        migrations.CreateModel(
            name='TotpDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(default=pyotp.random_base32, editable=False, max_length=32, verbose_name='Secret TOTP')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Confirmé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='totp_device', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'appareil TOTP',
                'verbose_name_plural': 'appareils TOTP',
            },
        ),
        migrations.CreateModel(
            name='TotpBackupCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=128, verbose_name='Code (haché)')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Utilisé le')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_codes', to='forge_auth.totpdevice')),
            ],
            options={
                'verbose_name': 'code de secours TOTP',
                'verbose_name_plural': 'codes de secours TOTP',
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50, verbose_name='Fournisseur')),
                ('subject', models.CharField(max_length=255, verbose_name='Identifiant chez le fournisseur (sub)')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail communiqué par le fournisseur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Lié le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'compte social',
                'verbose_name_plural': 'comptes sociaux',
                'unique_together': {('provider', 'subject')},
            },
        ),
    ]
